package br.com.bicicletarioapp.view;

import br.com.bicicletarioapp.model.Aluguel;
import br.com.bicicletarioapp.model.Bicicleta;
import br.com.bicicletarioapp.model.Cliente;
import br.com.bicicletarioapp.model.Usuario;
import br.com.bicicletarioapp.repository.AluguelRepository;
import br.com.bicicletarioapp.repository.BicicletaRepository;
import br.com.bicicletarioapp.repository.ClienteRepository;
import br.com.bicicletarioapp.repository.IAluguelRepository;
import br.com.bicicletarioapp.repository.IBicicletaRepository;
import br.com.bicicletarioapp.repository.IClienteRepository;
import br.com.bicicletarioapp.service.AluguelService;
import br.com.bicicletarioapp.service.BicicletaService;
import br.com.bicicletarioapp.service.ClienteService;
import br.com.bicicletarioapp.util.JPAUtil;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Id;
import java.lang.Long;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Alugueis extends javax.swing.JFrame {

    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtBicicletaId;
    private javax.swing.JTextField txtPrecoHora;

    /**
     * Creates new form Aluguel
     */
    public Alugueis() {
        initComponents();
        carregarAlugueis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GERENCIAR ALUGUÉIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, -1));

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 80, 32));

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, -1));

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, -1));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 120, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "cliente_id", "bicicleta_id ", "usuario_id", "hora_inicio", "hora_termino ", "preço_hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 70, 550, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        System.out.println("=== ORDEM DAS COLUNAS ===");
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            System.out.println("Coluna " + i + ": " + jTable1.getColumnName(i).trim());
        }
        System.out.println("========================");
        EntityManager em = null;
        try {
            em = JPAUtil.getEntityManager();

            AluguelService aluguelService = new AluguelService(em);
            IClienteRepository clienteRepository = new ClienteRepository(em);
            ClienteService clienteService = new ClienteService(clienteRepository);
            IBicicletaRepository bicicletaRepository = new BicicletaRepository(em);
            BicicletaService bicicletaService = new BicicletaService(bicicletaRepository);

            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Selecione uma linha na tabela.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // USE ESTES ÍNDICES - baseado na ordem real das colunas
            Object clienteIdObj = jTable1.getValueAt(selectedRow, 1);      // coluna 1: cliente_id
            Object bicicletaIdObj = jTable1.getValueAt(selectedRow, 2);    // coluna 2: bicicleta_id  
            Object usuarioIdObj = jTable1.getValueAt(selectedRow, 3);      // coluna 3: usuario_id
            Object horaInicioObj = jTable1.getValueAt(selectedRow, 4);     // coluna 4: hora_inicio
            Object horaTerminoObj = jTable1.getValueAt(selectedRow, 5);    // coluna 5: hora_termino
            Object precoHoraObj = jTable1.getValueAt(selectedRow, 6);      // coluna 6: preço_hora

// DEBUG CORRETO - mostre os valores reais que está usando
            System.out.println("DEBUG CORRETO - Valores lidos:");
            System.out.println("Coluna 1 (cliente_id): " + jTable1.getValueAt(selectedRow, 1));
            System.out.println("Coluna 2 (bicicleta_id): " + jTable1.getValueAt(selectedRow, 2));
            System.out.println("Coluna 3 (usuario_id): " + jTable1.getValueAt(selectedRow, 3));
            System.out.println("Coluna 4 (hora_inicio): " + jTable1.getValueAt(selectedRow, 4));
            System.out.println("Coluna 5 (hora_termino): " + jTable1.getValueAt(selectedRow, 5));
            System.out.println("Coluna 6 (preco_hora): " + jTable1.getValueAt(selectedRow, 6));

            if (clienteIdObj == null || bicicletaIdObj == null || horaInicioObj == null || horaTerminoObj == null || precoHoraObj == null) {
                JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Long clienteId = Long.valueOf(clienteIdObj.toString());
            Long bicicletaId = Long.valueOf(bicicletaIdObj.toString());
            String horaInicioStr = horaInicioObj.toString();
            String horaTerminoStr = horaTerminoObj.toString();
            Double precoHora = Double.valueOf(precoHoraObj.toString());

            LocalDateTime horaInicio = LocalDateTime.now();
            LocalDateTime horaTermino = horaInicio.plusHours(1);

            Cliente cliente = clienteService.buscarClientePorId(clienteId);
            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Cliente com ID " + clienteId + " não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            Bicicleta bicicleta = bicicletaService.buscarPorId(bicicletaId);
            if (bicicleta == null) {
                JOptionPane.showMessageDialog(this, "Bicicleta com ID " + bicicletaId + " não encontrada.", "Erro", JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            br.com.bicicletarioapp.model.Aluguel novoAluguel = new br.com.bicicletarioapp.model.Aluguel();
            novoAluguel.setCliente(cliente);
            novoAluguel.setBicicleta(bicicleta);
            Usuario usuario = null;
            novoAluguel.setUsuario(usuario);
            novoAluguel.setPrecoHora(BigDecimal.valueOf(precoHora));

            try {
                aluguelService.registrarAluguel(novoAluguel);
            } catch (IllegalStateException e) {
                if (e.getMessage().contains("Transaction not successfully started")) {
                    // Ignora apenas erros de transação, pois o insert funcionou
                    System.out.println("Aluguel salvo com sucesso (aviso de transação ignorado)");
                } else {
                    throw e; // Re-lança outras exceções
                }
            }
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Aluguel adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            em.close();
            carregarAlugueis();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro de formato numérico: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao adicionar o aluguel: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            e.printStackTrace();
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }
        }


    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        CalculoAluguel telaCalculo = new CalculoAluguel();
        telaCalculo.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        EntityManager em = null;
        try {
            em = JPAUtil.getEntityManager();

            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um aluguel para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Obtenha o ID do aluguel selecionado (coluna 0: id)
            Object idObj = jTable1.getValueAt(selectedRow, 0);
            if (idObj == null) {
                JOptionPane.showMessageDialog(this, "Selecione um aluguel válido para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Long aluguelId = Long.valueOf(idObj.toString());

            // Confirmação antes de excluir
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja excluir o aluguel ID: " + aluguelId + "?",
                    "Confirmar Exclusão",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // Use o repositório diretamente para excluir
            IAluguelRepository aluguelRepository = new AluguelRepository(em);
            aluguelRepository.delete(aluguelId);

            JOptionPane.showMessageDialog(this, "Aluguel excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // Recarregue a tabela
            carregarAlugueis();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido selecionado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir aluguel: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            if (em != null && em.isOpen()) {
                em.close();
            }

        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluguel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alugueis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void carregarAlugueis() {
        EntityManager em = null;
        try {
            em = JPAUtil.getEntityManager();

            // CORREÇÃO: Use o repositório corretamente
            IAluguelRepository aluguelRepository = new AluguelRepository(em);
            AluguelService aluguelService = new AluguelService(em); // Passe o EntityManager

            List<br.com.bicicletarioapp.model.Aluguel> alugueis = aluguelService.listarAlugueis();

            // Limpa a tabela
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // Define um formatador para a data e hora
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            // Preenche a tabela
            for (br.com.bicicletarioapp.model.Aluguel aluguel : alugueis) {
                model.addRow(new Object[]{
                    aluguel.getId(),
                    aluguel.getCliente().getId(),
                    aluguel.getBicicleta().getId(),
                    aluguel.getUsuario() != null ? aluguel.getUsuario().getId() : null,
                    aluguel.getHoraInicio().format(formatter),
                    aluguel.getHoraTermino() != null ? aluguel.getHoraTermino().format(formatter) : "Em andamento",
                    aluguel.getPrecoHora()
                });
            }

            for (int i = 0; i < 15; i++) {
                model.addRow(new Object[]{null, null, null, null, null, null});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar aluguéis: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }
}
